stages:
  - deploy

deploy-to-server:
  stage: deploy
  image: python:3.13-slim
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y openssh-client rsync
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H -p $SSH_PORT "$SSH_HOST" >> ~/.ssh/known_hosts

  script:
    - mkdir -p deploy_temp
    - rsync -av --exclude='.git' --exclude='.venv' ./ deploy_temp/
    - tar -czf app.tar.gz -C deploy_temp .
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "mkdir -p $DEPLOY_PATH/models"
    - scp -P $SSH_PORT app.tar.gz $SSH_USER@$SSH_HOST:$DEPLOY_PATH/
    - scp -P $SSH_PORT "$BEST_PT_FILE" $SSH_USER@$SSH_HOST:$DEPLOY_PATH/models/best.pt
    - ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
        cd $DEPLOY_PATH &&
        tar -xzf app.tar.gz &&
        rm app.tar.gz &&
        docker-compose up -d --build
      "
